tunnel: c3970739-1e23-4640-b88a-b5c7741131c0
credentials-file: C:\Users\IIamHub3\.cloudflared\c3970739-1e23-4640-b88a-b5c7741131c0.json
ingress:
  - hostname: farmingsight.org
    service: http://localhost:8000
  - service: http_status:404
